In [118]:
import pandas as pd
import numpy as np
import sklearn

In [119]:
df = pd.read_csv("used_cars_data.csv")

In [120]:
df

      S.No.  ...  Price
0         0  ...   1.75
1         1  ...  12.50
2         2  ...   4.50
3         3  ...   6.00
4         4  ...  17.74
...     ...  ...    ...
7248   7248  ...    NaN
7249   7249  ...    NaN
7250   7250  ...    NaN
7251   7251  ...    NaN
7252   7252  ...    NaN

[7253 rows x 14 columns]

In [121]:
df["Name"].nunique()

2041

In [122]:
df["Fuel_Type"].value_counts()

Fuel_Type
Diesel      3852
Petrol      3325
CNG           62
LPG           12
Electric       2
Name: count, dtype: int64

In [123]:
df["Owner_Type"].value_counts()

Owner_Type
First             5952
Second            1152
Third              137
Fourth & Above      12
Name: count, dtype: int64

1. One hot Encoding using Pandas

In [124]:
pd.get_dummies(df,columns = ["Fuel_Type","Owner_Type"])

      S.No.  ... Owner_Type_Third
0         0  ...            False
1         1  ...            False
2         2  ...            False
3         3  ...            False
4         4  ...            False
...     ...  ...              ...
7248   7248  ...            False
7249   7249  ...            False
7250   7250  ...            False
7251   7251  ...             True
7252   7252  ...            False

[7253 rows x 21 columns]

2. K-1 One Hot Encoding

In [125]:
pd.get_dummies(df,columns=["Fuel_Type","Owner_Type"],drop_first = True)

      S.No.  ... Owner_Type_Third
0         0  ...            False
1         1  ...            False
2         2  ...            False
3         3  ...            False
4         4  ...            False
...     ...  ...              ...
7248   7248  ...            False
7249   7249  ...            False
7250   7250  ...            False
7251   7251  ...             True
7252   7252  ...            False

[7253 rows x 19 columns]

# OneHotEncoding Using Sklearn

In [126]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    df.iloc[:, 0:12], 
    df.iloc[:, -1], 
    test_size=0.2, 
    random_state=0
)

In [127]:
X_test.head()

      S.No.                       Name   Location  ...   Engine       Power Seats
4178   4178       Hyundai Verna 1.6 SX  Bangalore  ...  1582 CC  126.32 bhp   5.0
528     528  Maruti Swift VXI Optional      Kochi  ...  1197 CC   81.80 bhp   5.0
7235   7235   Maruti Vitara Brezza ZDi      Kochi  ...  1248 CC    88.5 bhp   5.0
4658   4658       Maruti Alto LXi BSII       Pune  ...   796 CC    46.3 bhp   5.0
4281   4281           Renault KWID RXT       Pune  ...   799 CC    53.3 bhp   5.0

[5 rows x 12 columns]

In [128]:
from sklearn .preprocessing import OneHotEncoder

In [129]:
ohe = OneHotEncoder(drop = "first", sparse_output= False, dtype = np.int32)

In [130]:
X_train_new = ohe.fit_transform(X_train[["Fuel_Type","Owner_Type"]])

In [131]:
X_train_new.shape

(5802, 7)

In [132]:
X_test_new = ohe.fit_transform(X_test[["Fuel_Type","Owner_Type"]])

In [133]:
np.hstack((X_train[["Fuel_Type","Owner_Type"]].values, X_train_new))

array([['Petrol', 'First', 0, ..., 0, 0, 0],
       ['Petrol', 'First', 0, ..., 0, 0, 0],
       ['Petrol', 'Second', 0, ..., 0, 1, 0],
       ...,
       ['Diesel', 'First', 1, ..., 0, 0, 0],
       ['Diesel', 'First', 1, ..., 0, 0, 0],
       ['Diesel', 'First', 1, ..., 0, 0, 0]],
      shape=(5802, 9), dtype=object)