##DataFrame

In [1]:
import numpy as np 
import pandas as pd

In [3]:
data = {
    'Name': ['John', 'Anna', 'Peter', 'Linda'],
    'Age': [28, 34, 29, 42],
    'City': ['New York', 'Paris', 'Berlin', 'London'],
    'Salary': [65000, 70000, 62000, 85000]
}

pd.DataFrame(data)

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [30]:
data_list = [
    ['John', 28, 'New York', 65000],
    ['Anna', 34, 'Paris', 70000],
    ['Peter', 29, 'Berlin', 62000],
    ['Linda', 42, 'London', 85000]
]
df2 = pd.DataFrame(data_list)
columns = ['Name','Age', 'City', 'Salary']
df2 = pd.DataFrame(data_list, columns=columns)
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [31]:
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

##Indexing

In [34]:
df2["Name"]

0     John
1     Anna
2    Peter
3    Linda
Name: Name, dtype: str

In [37]:
df2[["Name", "City", 'Salary']]

    Name      City  Salary
0   John  New York   65000
1   Anna     Paris   70000
2  Peter    Berlin   62000
3  Linda    London   85000

In [43]:
df2["Designation"] = ['Engineer', 'Manager','Doctor', 'Analyst']

df2

    Name  Age      City  Salary Designation
0   John   28  New York   65000    Engineer
1   Anna   34     Paris   70000     Manager
2  Peter   29    Berlin   62000      Doctor
3  Linda   42    London   85000     Analyst

In [55]:
df2.drop("Designation", axis=1, inplace = True)

In [56]:
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [59]:
df2.loc[2]

Name       Peter
Age           29
City      Berlin
Salary     62000
Name: 2, dtype: object

In [72]:
df2.loc[[2,3]][["Name", "Age"]]

    Name  Age
2  Peter   29
3  Linda   42

### Condition Statements

In [73]:
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

#only people whos age is above 30

In [74]:
df2[df2["Age"] > 30]

    Name  Age    City  Salary
1   Anna   34   Paris   70000
3  Linda   42  London   85000

In [76]:
# PERSON HAS TO BE FROM NEW YORK
df2[df2["City"] == 'New York']

   Name  Age      City  Salary
0  John   28  New York   65000

In [81]:
#age above 30 and city london
df2[(df2["Age"] > 30) & (df2['City'] == "London")]

    Name  Age    City  Salary
3  Linda   42  London   85000