In [1]:
import numpy as np
import pandas as pd

## Finding Missing Data

In [14]:
data = {
    'A': [1, 2, np.nan, 4, 5],
    'B': [2, 2, 3, 4, 5],
    'C': [1, 2, 3, np.nan, np.nan],
    'D': [1, np.nan, np.nan, np.nan, 5]

}
df = pd.DataFrame(data)

In [16]:
df

     A  B    C    D
0  1.0  2  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [10]:
df.isna()

       A      B      C      D
0  False   True  False  False
1  False  False  False   True
2   True  False  False   True
3  False  False   True   True
4  False  False   True  False

In [8]:
df.isna().sum()

A    1
B    1
C    2
D    3
dtype: int64

In [11]:
df.isna().any()

A    True
B    True
C    True
D    True
dtype: bool

## Removing Missing Data

In [12]:
df

     A    B    C    D
0  1.0  NaN  1.0  1.0
1  2.0  2.0  2.0  NaN
2  NaN  3.0  3.0  NaN
3  4.0  4.0  NaN  NaN
4  5.0  5.0  NaN  5.0

In [15]:
df.dropna()

     A  B    C    D
0  1.0  2  1.0  1.0

In [27]:
df.dropna(thresh=3)

     A  B    C    D
0  1.0  2  1.0  1.0
1  2.0  2  2.0  NaN
4  5.0  5  NaN  5.0

## FIlling the missing data

In [28]:
df

     A  B    C    D
0  1.0  2  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [29]:
df.fillna(0)

     A  B    C    D
0  1.0  2  1.0  1.0
1  2.0  2  2.0  0.0
2  0.0  3  3.0  0.0
3  4.0  4  0.0  0.0
4  5.0  5  0.0  5.0

In [31]:
values = {'A': 0,"B":1,"C":9,"D":8}

In [32]:
df

     A  B    C    D
0  1.0  2  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [35]:
df.fillna(values)

     A  B    C    D
0  1.0  2  1.0  1.0
1  2.0  2  2.0  8.0
2  0.0  3  3.0  8.0
3  4.0  4  9.0  8.0
4  5.0  5  9.0  5.0

In [37]:
df.fillna(df.mean())

     A  B    C    D
0  1.0  2  1.0  1.0
1  2.0  2  2.0  3.0
2  3.0  3  3.0  3.0
3  4.0  4  2.0  3.0
4  5.0  5  2.0  5.0