In [2]:
import pandas as pd

In [4]:
df = pd.read_csv("Companies.csv", on_bad_lines = "skip")

How data look like?

In [5]:
df

,name,rating,reviews,Type_Location,Top_rated_for
0,TCS ...,3.3,(1.1L),IT Services & Consulting | Bengaluru +444 oth...,Job Security
1,Infosys ...,3.5,(49k),IT Services & Consulting | Bengaluru +246 oth...,Job Security
2,Genpact ...,3.6,(42.5k),Analytics & KPO | Hyderabad +181 other locati...,Job Security
3,Concentrix Corporation ...,3.6,(32.4k),BPO | Bengaluru +183 other locations ...,Job Security
4,Bharti Airtel ...,3.8,(17.1k),Telecom | Gurugram +794 other locations ...,Promotions
...,...,...,...,...,...
365,Micromax Informatics ...,3.9,(567),Consumer Electronics & Appliances | New Delhi...,Work Life Balance
366,AM Infoweb ...,3.8,(558),BPO | Pune +8 other locations ...,Skill Development
367,Haldiram Snacks ...,3.9,(558),Food Processing | Noida +69 other locations ...,Promotions
368,WPP Media ...,3.6,(558),Marketing & Advertising | Gurugram +27 other ...,Job Security
369,Bharat Fritz Werner ...,3.9,(555),Industrial Machinery | Bengaluru +18 other lo...,Skill Development

How big is the Data?

In [6]:
df.shape

(370, 5)

What is the data type of columns?

In [8]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 370 entries, 0 to 369
Data columns (total 5 columns):
 #   Column                                                                               Non-Null Count  Dtype
---  ------                                                                               --------------  -----
 0   name                                                                                 370 non-null    str
 1    rating                                                                              370 non-null    float64
 2    reviews                                                                             370 non-null    str
 3    Type_Location                                                                       370 non-null    str
 4    Top_rated_for                                                                       370 non-null    str
dtypes: float64(1), str(4)
memory usage: 81.2 KB

Are there is missing values?

In [11]:
df.isnull().sum()

name                                                                                   0
 rating                                                                                0
 reviews                                                                               0
 Type_Location                                                                         0
 Top_rated_for                                                                         0
dtype: int64

how does data look mathematically?

In [12]:
df.describe()

           rating
count  370.000000
mean     3.730541
std      0.146549
min      3.000000
25%      3.700000
50%      3.800000
75%      3.800000
max      4.000000

Are there duplicate Values?

In [14]:
df.duplicated().sum()

np.int64(1)

In [16]:
df.drop_duplicates()

,name,rating,reviews,Type_Location,Top_rated_for
0,TCS ...,3.3,(1.1L),IT Services & Consulting | Bengaluru +444 oth...,Job Security
1,Infosys ...,3.5,(49k),IT Services & Consulting | Bengaluru +246 oth...,Job Security
2,Genpact ...,3.6,(42.5k),Analytics & KPO | Hyderabad +181 other locati...,Job Security
3,Concentrix Corporation ...,3.6,(32.4k),BPO | Bengaluru +183 other locations ...,Job Security
4,Bharti Airtel ...,3.8,(17.1k),Telecom | Gurugram +794 other locations ...,Promotions
...,...,...,...,...,...
365,Micromax Informatics ...,3.9,(567),Consumer Electronics & Appliances | New Delhi...,Work Life Balance
366,AM Infoweb ...,3.8,(558),BPO | Pune +8 other locations ...,Skill Development
367,Haldiram Snacks ...,3.9,(558),Food Processing | Noida +69 other locations ...,Promotions
368,WPP Media ...,3.6,(558),Marketing & Advertising | Gurugram +27 other ...,Job Security
369,Bharat Fritz Werner ...,3.9,(555),Industrial Machinery | Bengaluru +18 other lo...,Skill Development

How is the correlation between columns?

In [23]:
df.corr

<bound method DataFrame.corr of     name                                                                              \
0    TCS                                           ...
1    Infosys                                       ...
2    Genpact                                       ...
3    Concentrix Corporation                        ...
4    Bharti Airtel                                 ...
..                                                 ...
365  Micromax Informatics                          ...
366  AM Infoweb                                    ...
367  Haldiram Snacks                               ...
368  WPP Media                                     ...
369  Bharat Fritz Werner                           ...

      rating   reviews  \
0        3.3   (1.1L)
1        3.5   (49k)
2        3.6   (42.5k)
3        3.6   (32.4k)
4        3.8   (17.1k)
..       ...       ...
365      3.9   (567)
366      3.8   (558)
367      3.9   (558)
368      3.6   (558)
369      3.9   (555)

     Type_Location                                                                       \
0     IT Services & Consulting | Bengaluru +444 oth...
1     IT Services & Consulting | Bengaluru +246 oth...
2     Analytics & KPO | Hyderabad +181 other locati...
3     BPO | Bengaluru +183 other locations         ...
4     Telecom | Gurugram +794 other locations      ...
..                                                 ...
365   Consumer Electronics & Appliances | New Delhi...
366   BPO | Pune +8 other locations                ...
367   Food Processing | Noida +69 other locations  ...
368   Marketing & Advertising | Gurugram +27 other ...
369   Industrial Machinery | Bengaluru +18 other lo...

          Top_rated_for
0          Job Security
1          Job Security
2          Job Security
3          Job Security
4            Promotions
..                  ...
365   Work Life Balance
366   Skill Development
367          Promotions
368        Job Security
369   Skill Development

[370 rows x 5 columns]>